
package net.loquequiera2;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "IExternalGenerarDocumentoService", targetNamespace = "http://ar.gob.gcaba.gedo.satra.services.external.generardocumento/", wsdlLocation = "http://mule-cap.neuquen.gov.ar/GEDOServices/generarDocumento?wsdl")
public class IExternalGenerarDocumentoService_Service
    extends Service
{

    private final static URL IEXTERNALGENERARDOCUMENTOSERVICE_WSDL_LOCATION;
    private final static WebServiceException IEXTERNALGENERARDOCUMENTOSERVICE_EXCEPTION;
    private final static QName IEXTERNALGENERARDOCUMENTOSERVICE_QNAME = new QName("http://ar.gob.gcaba.gedo.satra.services.external.generardocumento/", "IExternalGenerarDocumentoService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://mule-cap.neuquen.gov.ar/GEDOServices/generarDocumento?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        IEXTERNALGENERARDOCUMENTOSERVICE_WSDL_LOCATION = url;
        IEXTERNALGENERARDOCUMENTOSERVICE_EXCEPTION = e;
    }

    public IExternalGenerarDocumentoService_Service() {
        super(__getWsdlLocation(), IEXTERNALGENERARDOCUMENTOSERVICE_QNAME);
    }

    public IExternalGenerarDocumentoService_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), IEXTERNALGENERARDOCUMENTOSERVICE_QNAME, features);
    }

    public IExternalGenerarDocumentoService_Service(URL wsdlLocation) {
        super(wsdlLocation, IEXTERNALGENERARDOCUMENTOSERVICE_QNAME);
    }

    public IExternalGenerarDocumentoService_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, IEXTERNALGENERARDOCUMENTOSERVICE_QNAME, features);
    }

    public IExternalGenerarDocumentoService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public IExternalGenerarDocumentoService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns IExternalGenerarDocumentoService
     */
    @WebEndpoint(name = "IExternalGenerarDocumentoServicePort")
    public IExternalGenerarDocumentoService getIExternalGenerarDocumentoServicePort() {
        return super.getPort(new QName("http://ar.gob.gcaba.gedo.satra.services.external.generardocumento/", "IExternalGenerarDocumentoServicePort"), IExternalGenerarDocumentoService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IExternalGenerarDocumentoService
     */
    @WebEndpoint(name = "IExternalGenerarDocumentoServicePort")
    public IExternalGenerarDocumentoService getIExternalGenerarDocumentoServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ar.gob.gcaba.gedo.satra.services.external.generardocumento/", "IExternalGenerarDocumentoServicePort"), IExternalGenerarDocumentoService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (IEXTERNALGENERARDOCUMENTOSERVICE_EXCEPTION!= null) {
            throw IEXTERNALGENERARDOCUMENTOSERVICE_EXCEPTION;
        }
        return IEXTERNALGENERARDOCUMENTOSERVICE_WSDL_LOCATION;
    }

}
