
package net.loquequiera2;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IExternalGenerarDocumentoService", targetNamespace = "http://ar.gob.gcaba.gedo.satra.services.external.generardocumento/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IExternalGenerarDocumentoService {


    /**
     * 
     * @param request
     * @return
     *     returns net.loquequiera2.ResponseExternalGenerarDocumento
     * @throws ClavesFaltantesException_Exception
     * @throws ParametroInvalidoException_Exception
     * @throws ErrorGeneracionDocumentoException_Exception
     * @throws CantidadDatosNoSoportadaException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "generarDocumentoGEDO", targetNamespace = "http://ar.gob.gcaba.gedo.satra.services.external.generardocumento/", className = "net.loquequiera2.GenerarDocumentoGEDO")
    @ResponseWrapper(localName = "generarDocumentoGEDOResponse", targetNamespace = "http://ar.gob.gcaba.gedo.satra.services.external.generardocumento/", className = "net.loquequiera2.GenerarDocumentoGEDOResponse")
    public ResponseExternalGenerarDocumento generarDocumentoGEDO(
        @WebParam(name = "request", targetNamespace = "")
        RequestExternalGenerarDocumento request)
        throws CantidadDatosNoSoportadaException_Exception, ClavesFaltantesException_Exception, ErrorGeneracionDocumentoException_Exception, ParametroInvalidoException_Exception
    ;

    /**
     * 
     * @param request
     * @return
     *     returns net.loquequiera2.ResponseExternalGenerarDocumento
     * @throws ClavesFaltantesException_Exception
     * @throws ParametroInvalidoException_Exception
     * @throws ErrorGeneracionDocumentoException_Exception
     * @throws CantidadDatosNoSoportadaException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "generarDocumentoUsuarioExterno", targetNamespace = "http://ar.gob.gcaba.gedo.satra.services.external.generardocumento/", className = "net.loquequiera2.GenerarDocumentoUsuarioExterno")
    @ResponseWrapper(localName = "generarDocumentoUsuarioExternoResponse", targetNamespace = "http://ar.gob.gcaba.gedo.satra.services.external.generardocumento/", className = "net.loquequiera2.GenerarDocumentoUsuarioExternoResponse")
    public ResponseExternalGenerarDocumento generarDocumentoUsuarioExterno(
        @WebParam(name = "request", targetNamespace = "")
        RequestExternalGenerarDocumentoUsuarioExterno request)
        throws CantidadDatosNoSoportadaException_Exception, ClavesFaltantesException_Exception, ErrorGeneracionDocumentoException_Exception, ParametroInvalidoException_Exception
    ;

}
