
package net.loquequiera2;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "ParametroInvalidoException", targetNamespace = "http://ar.gob.gcaba.gedo.satra.services.external.generardocumento/")
public class ParametroInvalidoException_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private ParametroInvalidoException faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public ParametroInvalidoException_Exception(String message, ParametroInvalidoException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public ParametroInvalidoException_Exception(String message, ParametroInvalidoException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: net.loquequiera2.ParametroInvalidoException
     */
    public ParametroInvalidoException getFaultInfo() {
        return faultInfo;
    }

}
